import {jsPDF} from "jspdf"

function addRectangle (x, y, color, pdf) {
    let r = color[0]
    let g = color[1]
    let b = color[2]

    pdf.setFillColor(r, g, b)
    pdf.rect(x, y, 50, 50, 'F')

}

function createPDF (colors) {
    const rgbs = colors.rgbs
    const hexs = colors.hexs
    const hsvs = colors.hsvs

    const pdf = new jsPDF({unit: 'mm',
        format: 'a4'})

    pdf.setFontSize(12)

    let x = 30
    let y = 30

    for (const idx in rgbs) {
        addRectangle(x, y, rgbs[idx], pdf)
        x += 50

        if (idx == 2) {
            x = 30
            y = 80
        }
    }

    let d1 = 45
    let d2 = 50
    let d3 = 5
    let d4 = 16

    let text_x1 = 25
    let text_x2 = text_x1 + d1

    let text_x3 = text_x1 + d1 * 2
    let text_x4 = text_x3 + d2

    let text_y = 160

    pdf.text("Hex", text_x2, text_y, {align: "center"})
    pdf.text("RGB", text_x3, text_y, {align: "center"})
    pdf.text("HSV", text_x4, text_y, {align: "center"})

    for (const idx in hexs) {
        text_y += 10

        pdf.text(`Color ${Number(idx)+1}:`, text_x1, text_y)
        pdf.text(`${hexs[idx]}`, text_x2, text_y, {align: "center"})

        
        // prints ( r, g, b )
        pdf.text("(", text_x3-d4, text_y, {align: "center"})

        pdf.text(`${rgbs[idx][0]}, `, text_x3-d3, text_y, {align: "right"})
        pdf.text(`${rgbs[idx][1]}`, text_x3, text_y, {align: "center"})
        pdf.text(`, ${rgbs[idx][2]}`, text_x3+d3, text_y, {align: "left"})

        pdf.text(")", text_x3+d4, text_y, {align: "center"})


        // prints ( h, s, v )
        pdf.text("(", text_x4-d4, text_y, {align: "center"})

        pdf.text(`${hsvs[idx][0]}, `, text_x4-d3, text_y, {align: "right"})
        pdf.text(`${hsvs[idx][1]}%`, text_x4, text_y, {align: "center"})
        pdf.text(`, ${hsvs[idx][2]}%`, text_x4+d3, text_y, {align: "left"})

        pdf.text(")", text_x4+d4+2, text_y, {align: "center"})
    }

    pdf.setFontSize(9)
    pdf.text("Color scheme generated by Sara Harder's color scheme generator program", 200, 287, {align: "right"})


    pdf.save("color-scheme.pdf")

}

export default createPDF