import {jsPDF} from "jspdf"

function addSquare (x, y, color, pdf) {
    // adds a colored square to the pdf in x, y position
    let [r, g, b] = color

    pdf.setFillColor(r, g, b)
    pdf.rect(x, y, 50, 50, 'F')

}

function createPDF (colors) {
    // generates a pdf with the colors and color info
    const rgbs = colors.rgbs
    const hexs = colors.hexs
    const hsvs = colors.hsvs

    // create pdf and establish format
    const pdf = new jsPDF({unit: 'mm',
        format: 'a4'})
    pdf.setFontSize(12)

    let [x, y] = [30, 30]

    // adds a color square for each color
    for (const idx in rgbs) {
        addSquare(x, y, rgbs[idx], pdf)
        x += 50

        if (idx == 2) {
            [x, y] = [30, 80]
        }
    }

    // the d's represent the differences (in mm) between text elements
    let [d1, d2, d3, d4] = [45, 50, 5, 16]
    // the x's represent the distance left (in mm) that text should be positioned
    let [x1, x2, x3, x4] = [25, x1+d1, x1+d1*2, x3+d2]
    // yt represents the height at which the text should be positioned
    let yt = 160

    // adds column labels for the color info
    pdf.text("Hex", x2, yt, {align: "center"})
    pdf.text("RGB", x3, yt, {align: "center"})
    pdf.text("HSV", x4, yt, {align: "center"})

    for (const idx in hexs) {
        yt += 10

        // prints "Color i: hex"
        pdf.text(`Color ${Number(idx)+1}:`,     x1, yt)
        pdf.text(`${hexs[idx]}`,                x2, yt,     {align: "center"})

        
        // prints ( r, g, b )
        pdf.text("(",                           x3-d4, yt,  {align: "center"})
        pdf.text(`${rgbs[idx][0]}, `,           x3-d3, yt,  {align: "right"})
        pdf.text(`${rgbs[idx][1]}`,             x3, yt,     {align: "center"})
        pdf.text(`, ${rgbs[idx][2]}`,           x3+d3, yt,  {align: "left"})
        pdf.text(")",                           x3+d4, yt,  {align: "center"})


        // prints ( h, s, v )
        pdf.text("(",                           x4-d4, yt,  {align: "center"})
        pdf.text(`${hsvs[idx][0]}, `,           x4-d3, yt,  {align: "right"})
        pdf.text(`${hsvs[idx][1]}%`,            x4, yt,     {align: "center"})
        pdf.text(`, ${hsvs[idx][2]}%`,          x4+d3, yt,  {align: "left"})
        pdf.text(")",                           x4+d4+2, yt, {align: "center"})
    }

    pdf.setFontSize(9)
    pdf.text("Color scheme generated by Sara Harder's color scheme generator program", 200, 287, {align: "right"})


    pdf.save("color-scheme.pdf")

}

export default createPDF